#!/usr/bin/env bash
set -e
set -u

#-------------------------------------------------------------------------------
ficherotmp(){
#-------------------------------------------------------------------------------
	if [[ -e /tmp/clipboard ]]; then
	  exec cat /tmp/clipboard
	else
	  echo ''
	fi
}
#-------------------------------------------------------------------------------
if [ -z ${DISPLAY+x} ]; then
	ficherotmp
else
	if hash pbpaste 2>/dev/null; then
	  exec pbpaste
	elif hash xclip 2>/dev/null; then
	  exec xclip -selection clipboard -o
	else
		ficherotmp
	fi
fi
